name: git-django-cloud-poc


on:
  push:
    branches: [dev, uat, prod]
  pull_request:
    branches: [dev, uat, prod]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-east4
#   SERVICE_NAME:oms-django-git-poc-dev
#   if: github.ref == 'refs/heads/uat'
#     SERVICE_NAME:oms-django-git-poc-uat
#   if: github.ref == 'refs/heads/dev'
#     SERVICE_NAME:oms-django-git-poc-dev
  
    


jobs:
  setup-build-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - uses: actions/checkout@v3

        
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
#        version: '290.0.1'
        version: '318.0.0'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

#     steps:
    - name: Configuration for main branch
      if: ${{ github.ref == 'refs/heads/uat' }}
       SERVICE_NAME:oms-django-git-poc-uat
    - name: Configuration for main branch
      if: ${{ github.ref == 'refs/heads/dev' }}
       SERVICE_NAME:oms-django-git-poc-dev
       
    # Build and push image to Google Container Registry	   

    - name: Build and Push Container
      run: |-
        gcloud builds submit \
          --quiet \
          --tag gcr.io/${{ env.PROJECT_ID }}/${{ SERVICE_NAME }}:${{  github.sha }}
          
    # Deploy image to Cloud Run
    
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --quiet \
          --region ${{ env.RUN_REGION }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ SERVICE_NAME }}:${{  github.sha }} \
          --platform "managed" \
          --allow-unauthenticated
